x-REACT_APP_DOMAIN: &REACT_APP_DOMAIN
  REACT_APP_DOMAIN: ${REACT_APP_DOMAIN} # Set in host shell environment: http://localhost 

x-MONGO_CONNECTION_STRING: &MONGO_CONNECTION_STRING
  MONGO_CONNECTION_STRING: ${MONGO_CONNECTION_STRING}               # CLOUD
  # MONGO_CONNECTION_STRING: mongodb://admin:admin@mongodb:27017/   # LOCAL  

x-GROQ_API_KEY: &GROQ_API_KEY
  GROQ_API_KEY: ${GROQ_API_KEY} # Pulled from host shell environment

######################################################################################

version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      <<: *REACT_APP_DOMAIN
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      <<: [*REACT_APP_DOMAIN,*MONGO_CONNECTION_STRING,*GROQ_API_KEY]
    depends_on:
      -  mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: admin
    restart: unless-stopped